- electionleaflets/templates/leaflets/full.html
- electionleaflets/templates/leaflets/full_all.html
- electionleaflets/templates/leaflets/image_crop.html
- electionleaflets/templates/leaflets/image_rotate.html
Should fix #41 by making sure it handles the default (of None).  
Presumably titles are missing on non-legacy leaflets because it isn't collected.
> Template leaflet titles

- electionleaflets/apps/constituencies/forms.py
- electionleaflets/apps/constituencies/views.py
If the user specified a well-structured, but non-existent postcode, bad things happened.
Now only good things happen because we added the validation in the form rather than after form validation.
Closes #34
> Invalid postcode on constituency page

- electionleaflets/apps/constituencies/views.py
Should fix #42 by changing ordering from number of leaflets desc to name.
This is a cached view, so probably won't show up straight-away.
> Changes the constituency ordering to be alphabetic

- electionleaflets/templates/leaflets/leaflet.html
Adds an extra parent div, so that the map is confined to that, instead
of the whole leaflet_map section.
Fixes #63
> Ensure that the leaflet map doesn't block the constituency link

- electionleaflets/apps/leaflets/migrations/0001_initial.py
- electionleaflets/apps/people/migrations/0001_initial.py
Use the latest migration from the `uk_poltical_parties` app.
`0005_auto_20160403_1447` doesn’t exist there.
> Fix migration dependencies

- .travis.yml
The `script` key in `.travis.yml` needs an array if multiple test
scripts should be run. As it was, the harvest script was overriding the
nosetest script.
`leaflets` isn’t a valid harvest attribute, so no tests were running.
This now runs all features.
> Make Travis actually run tests

- electionleaflets/assets-src/javascript/app/app.js
- electionleaflets/media/javascript/electionleaflets.main.min.js
- electionleaflets/settings/base.py
- requirements/dev.txt
Stamen uses Fastly to serve tiles over SSL. There’s no need to serve
them over HTTP in dev mode, so just use Fastly over SSL regardless.
Fixes #112
> Fetch Stamen tiles over SSL

- requirements/base.txt
1.4.8 depends on South, which is unsupported in Django 1.9. Also remove
the duplicate requirement.
This issue was introduced in e0ca396f1ea2ee91fe1b0d8d9c68ec46b08cdcf4
> Upgrade django-extensions to 1.7.9

- electionleaflets/apps/api/views.py
In PR #125 I accidentally broke the
- /stats
- /latest_by_constituency and
- /latest_by_person endpoints
(sorry)
This fixes the permissions and stops them from throwing
`Cannot apply DjangoModelPermissions on a view that does not set .queryset or have a .get_queryset() method.`
@symroe - Getting this merged and deployed is reasonably important as it is currently causing the leaflets import on WhoCIVF to fail :(
(cc @annapowellsmith )
> Fix API permission errors

- electionleaflets/templates/account/email.html
- electionleaflets/templates/account/email_confirm.html
- electionleaflets/templates/account/login.html
- electionleaflets/templates/account/logout.html
- electionleaflets/templates/account/password_change.html
- electionleaflets/templates/account/password_reset.html
- electionleaflets/templates/account/password_reset_from_key.html
- electionleaflets/templates/account/password_set.html
- electionleaflets/templates/account/signup.html
- electionleaflets/templates/account/signup_closed.html
- electionleaflets/templates/account/verified_email_required.html
`url` isn't in `future` in Django 1.9, so this throws an error.
> Fix login on frontend

- electionleaflets/apps/leaflets/views.py
- electionleaflets/settings/zappa.py
- electionleaflets/third_party/s3_lambda_storage.py
We used to need a subclassed storage backend for Lambda as boto3 didn't
support Session Tokens. These are now supported out of the box so we
can use vanilla S3Boto3Storage. We still need a subclass to set the
location for static files.
> Fix storage backends

- electionleaflets/apps/api/serializers.py
- electionleaflets/apps/api/views.py
- electionleaflets/templates/leaflets/leaflet.html
We've removed the `image_text` field which was unpopulated, so we
shouldn't try and serialise it.
Leaflets don't have an `owner` so don' t use it to check permissions.
Use a relative URL for the JSON link on the leaflet page, the
`HTTP_HOST` on Lambda will not be the real EL URL and won't work.
> Fix leaflet JSON API

- serverless.yml
For working on DC locally, we use a `local.py`. When deploying using
`sls`, we zip the local working copy, which may include local settings.
This explicitly specifies the settings files we want to upload.
> Never accidentally deploy local settings

- electionleaflets/settings/base.py
For static assets that don't require compilation, we need to use the
main contrib finders rather than pipeline's ones, as there's no
rendering to be done.
> Fix using static assets from plugin apps

- electionleaflets/apps/leaflets/urls.py
- electionleaflets/apps/leaflets/views.py
- electionleaflets/templates/leaflets/upload_form/leaflet_upload_base.html
I suspect a POST request might fail if a large image exists in the
session, and POSTing it causes another error somewhere before the reset
can happen.
Using GET will remove the chance of POSTing large requests
> Use GET for resetting form rather than POST

- electionleaflets/settings/base_lambda.py
Currently leaflets allows anything in the host header. This makes the site vulnerable to a range of spoofing attacks. This PR tightens this setting up in line with (for example)
https://github.com/DemocracyClub/Website/blob/fd5b3e57fdef5caac46a7591344bd1ae3b7b3e5b/democracy_club/settings/aws_lambda.py#L17
The `APP_DOMAIN` env var is configured at
https://github.com/DemocracyClub/electionleaflets/blob/38b2f6c46a550ef84f49703df223a5c7e17784e5/template.yaml#L113
Build is failing because I branched off master. I just didn't want to lose sight of this one while I noticed it. We can cherry-pick this somewhere else if it is easier.
> reject fake host headers

- electionleaflets/apps/core/templatetags/markdown.py
- electionleaflets/apps/leaflets/tests/test_models.py
- electionleaflets/templates/base.html
- electionleaflets/templates/leaflets/leaflet.html
Ref https://democracy-club-gp.sentry.io/issues/5935314159
- Added Open Graph meta tags to Leaflet pages for improved social media sharing.
- Implemented conditional rendering for descriptions: displays only when available; otherwise, a default text will ensure compatibility with social media platforms.
- Renamed the markdown filter tag to prevent conflicts with Python, and updated tests to reflect this change.
> Fix markdown template tag error

- electionleaflets/apps/leaflets/views.py
- electionleaflets/templates/base.html
Ref https://democracy-club-gp.sentry.io/issues/5934903841?project=163593
The issue is that Lambda functions have a limited capacity for processing file sizes. To work around this, we upload files directly to S3 and then have the Lambda function process the image from there. Refactoring the process to use S3 without JavaScript—particularly for handling multiple file uploads—will require additional planning and design.
This update addresses the exception by notifying users of the JavaScript requirements. I’ve added this notice both on the home page and at the final step of the uploader process to ensure full coverage, even if users disable JavaScript midway through. While the latter may be unnecessary, it ensures this error won't occur again.
---
- To see the specific tasks where the Asana …
> JSON Decode Error

- .circleci/config.yml
- Pipfile.lock
There's a few things going on here:
1. We were re-running `pipenv sync` multiple times needlessly. The purpose of having a cached install step and restoring the cache is so that we don't need to do this.
2. We were uninstalling a package (poetry) that wasn't installed in the first place.
3. Run `pipenv verify` in CI to ensure our lockfile is in sync with the manifest. Also, it wasn't so fixed that by re-locking.
4. Originally I planned to add `./manage.py check` (system checks) and `./manage.py makemigrations --check` (make sure the migrations are up to date) to the build. Unfortunately I realised `./manage.py makemigrations --check` fails due to an issue with an abandoned package (which we can't fix here) not including migrations. For now I've commented that. I'm hoping we can bin that …
> Additional CI checks and tidy up

- electionleaflets/settings/base_lambda.py
- public-access-template.yaml
- thumbs/attach_lambda_triggers.py
Before this change, we would invoke the thumbs Lambda on each image response. 
This means bootstrapping Django every time we invoke the function, so it was very slow and cost more money / compute.
We can't conditionally invoke a Lambda@Edge function, but we can try S3 first and failover to the origin with the function attached. This is what I'm doing here.
> Optimise image serving

- pyproject.toml
- uv.lock
So... having said in the original review for this that I personally prefer putting the versions inline, it turns out the way to get renovate to play nice with VCS dependencies is to use `tool.uv.sources`. This is also what `uv add` does by default. So `tool.uv.sources` it is!
> switch VCS packages to use tool.uv.sources

- electionleaflets/urls.py
The default redirect URL includes the kwargs of the initial view.
We don't want this, and it causes a 500 without this change
> Always redirect to home with no args

- electionleaflets/templates/leaflets/leaflet.html
The 600 width image was too small, 1000 is a better size.
This is a thumb size we're already making, so there's no work to be done here in making new thumbnails
> Use larger image on leaflet pages

- electionleaflets/apps/core/helpers.py
- electionleaflets/apps/core/tests/test_helpers.py
- electionleaflets/apps/leaflets/forms.py
- electionleaflets/settings/base.py
Couple of things: 
I was wondering why I didn't get name appearing for leaflets I uploaded. Turns out the URL was wrong, so we weren't getting any results.
Second, I thought that we can afford to look back in time a lot longer: we do get leaflets uploaded by people who were elected in the last couple of years. This isn't a _very_ good solution, but it's better than it was, I think.
The more full solution would be to get a list of all names for the last election per seat, but that's a little out of scope for the time being :)
> Fix YNR URL and extend date range

- electionleaflets/apps/core/helpers.py
- electionleaflets/apps/core/tests/test_helpers.py
- electionleaflets/apps/leaflets/forms.py
- electionleaflets/apps/leaflets/views.py
- electionleaflets/settings/base_lambda.py
- template.yaml
Turns out we were rate limiting ourselves and also calling YNR too much.
1. Each time we called the `get_form_initial` we were calling YNR. `get_form_initial` is called for each form, so on the last step we were calling it three times. 
2. We'd not set an API key, so we were sleeping for 6 seconds each time. This mixed with actual time taken to process he view meant we were timing out the Lambda function, most of the time.
This change caches the YNR response on the form/session and also sets a key. So we should only call YNR once, and then not sleep when we're doing so.
TODO: set the SSM values before merging.
> Fix YNR API calls
